import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";
import { Geist, Geist_Mono, Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "OWES - Overwatch Esport Scouting",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className}`} suppressHydrationWarning>
      <body className="ow-page-bg ow-page-overlay min-h-screen text-ow-text">
        <TooltipProvider>
          <Providers>
            <SidebarProvider>
              <AppSidebar />
              <main>{children}</main>
            </SidebarProvider>
          </Providers>
        </TooltipProvider>
      </body>
    </html>
  );
}
